# Generated by Django 4.2.7 on 2023-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_new_movies_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_expiration',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
