version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass

  web:
    build: .
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASSWORD=dbpass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
  media: